name:                aoc-twenty-two
version:             0.1.0.0
github:              "githubuser/aoc-twenty-two"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc-twenty-two#readme>

dependencies:
- base >= 4.7 && < 5
- safe-exceptions
- bytestring
- text

default-extensions:
- OverloadedStrings
- RecordWildCards
- LambdaCase

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - split

executables:
  aoc-twenty-two-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - aoc-twenty-two


tests:
  aoc-twenty-two-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - tasty-discover  >= 4.2.2
    - tasty-hspec >= 1.2 
    - tasty 
    - hspec
    - aoc-twenty-two
